-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.departments
(
    dept_no character varying(4) NOT NULL,
    dept_name character varying(50) NOT NULL,
    PRIMARY KEY (dept_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.deptemployees
(
    emp_no integer NOT NULL,
    dept_no character varying(4) NOT NULL,
    PRIMARY KEY (emp_no, dept_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.employees
(
    emp_no integer NOT NULL,
    emp_title_id character varying(5) NOT NULL,
    birth_date date NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    sex character varying(1) NOT NULL,
    hire_date date NOT NULL,
    PRIMARY KEY (emp_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.deptmanagers
(
    emp_no integer NOT NULL,
    dept_no character varying(4) NOT NULL,
    PRIMARY KEY (emp_no, dept_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.salaries
(
    emp_no integer NOT NULL,
    salary integer NOT NULL,
    PRIMARY KEY (emp_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.titles
(
    title_id character varying(5) NOT NULL,
    title character varying(50) NOT NULL,
    PRIMARY KEY (title_id)
)
WITH (
    OIDS = FALSE
);

ALTER TABLE public.deptemployees
    ADD FOREIGN KEY (dept_no)
    REFERENCES public.departments (dept_no)
    NOT VALID;


ALTER TABLE public.deptmanagers
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no)
    NOT VALID;


ALTER TABLE public.deptmanagers
    ADD FOREIGN KEY (dept_no)
    REFERENCES public.departments (dept_no)
    NOT VALID;


ALTER TABLE public.deptemployees
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no)
    NOT VALID;


ALTER TABLE public.salaries
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (emp_title_id)
    REFERENCES public.titles (title_id)
    NOT VALID;

END;